name: ocr_nav
channels:
  - conda-forge
  - robostack-humble
dependencies:
  - python=3.11
  - ros-humble-desktop
  - pip
  - pip:
      - setuptools>=80.9.0
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - https://github.com/vllm-project/vllm/releases/download/v0.8.5/vllm-0.8.5+cu118-cp38-abi3-manylinux1_x86_64.whl
      - transformers>=4.46.3
      - tokenizers>=0.20.3
      - PyMuPDF
      - img2pdf
      - einops
      - easydict
      - addict 
      - Pillow
      - numpy
      - scipy
      - tqdm
      - pyvista
      - plyfile
      - open3d

prefix: /home/chuang/miniforge3/envs/ocr_nav
